version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify the Python version you need
    commands:
      - echo Creating virtual environment...
      - python -m venv venv
      - echo Activating virtual environment...
      - . venv/bin/activate
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build phase started...
      - . venv/bin/activate
      # Add any commands to run before the build, if necessary
  build:
    commands:
      - echo "Building the application"
      - python setup.py install
      - zip -r lambda.zip . 
  post_build:
    commands:
      - echo Post-build phase started...
      - . venv/bin/activate
      - echo Build completed on `date`
      # Add any commands you need after the build, e.g., packaging

artifacts:
  files:
    - appspec.yml
    - lambda.zip # Adjust if your Flask app is in a different directory

